interface UserProfile {
  email: string;
  full_name: string | null;
  trial_ends_at: string | null;
}

interface Finding {
  category: string;
  title: string;
  description: string;
  impact_amount_display: string | null;
}

export function generateCPAMemo(profile: UserProfile, findings: Finding[]): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const clientName = profile.full_name || profile.email.split('@')[0];

  let memo = `
================================================================================
                    SHADOW CFO - TAX DEDUCTION SUMMARY
                              ${date}
================================================================================

CLIENT: ${clientName}
EMAIL: ${profile.email}
PREPARED BY: Shadow CFO (Automated Analysis)

--------------------------------------------------------------------------------
                              EXECUTIVE SUMMARY
--------------------------------------------------------------------------------

This memo summarizes potential tax deductions identified through Shadow CFO's
automated financial analysis. These findings are provided for educational 
purposes and should be reviewed with your CPA before filing.

--------------------------------------------------------------------------------
                            OBBBA-RELATED DEDUCTIONS
--------------------------------------------------------------------------------

Under the One Big Beautiful Bill Act (OBBBA), several new deduction opportunities
may be available. The following items were identified in your financial profile:

`;

  findings.forEach((finding, index) => {
    memo += `
${index + 1}. ${finding.title}
   Category: ${finding.category.toUpperCase().replace('_', ' ')}
   Potential Savings: ${finding.impact_amount_display || 'TBD'}
   
   Details:
   ${finding.description}

`;
  });

  const totalPotential = findings.reduce((sum, f) => {
    const amount = parseFloat((f.impact_amount_display || '$0').replace(/[^0-9.-]/g, ''));
    return sum + amount;
  }, 0);

  memo += `
--------------------------------------------------------------------------------
                              TOTALS
--------------------------------------------------------------------------------

Total Potential Deduction: $${totalPotential.toLocaleString()}

NOTE: This amount is an estimate based on the information available. Actual
deductible amounts may vary based on your complete tax situation.

--------------------------------------------------------------------------------
                              DISCLAIMER
--------------------------------------------------------------------------------

This memo is provided for educational purposes only and does not constitute
tax advice. Shadow CFO is not a licensed tax professional. Please consult
with a qualified CPA or tax advisor to verify the deductibility of these
items and to ensure proper documentation for your tax return.

The estimates provided are based on:
- Information provided by you or obtained from your connected accounts
- Current tax law interpretation (as of the date above)
- General industry standards for similar financial situations

--------------------------------------------------------------------------------
                           RECOMMENDED NEXT STEPS
--------------------------------------------------------------------------------

1. Review this memo with your CPA during your next consultation
2. Gather supporting documentation for each identified deduction
3. Ensure all amounts match your actual financial records
4. Ask your CPA about any additional deductions not captured here

--------------------------------------------------------------------------------
                            ABOUT SHADOW CFO
--------------------------------------------------------------------------------

Shadow CFO helps individuals identify hidden financial leaks in their financial
lives, including tax inefficiencies. Our automated analysis reviews your
financial data to surface opportunities for savings.

Website: https://shadowcfo.com
Support: support@shadowcfo.com

================================================================================
                         Generated by Shadow CFO
                    Your Personal Financial Guardian
================================================================================
`;

  return memo;
}
